version: '3'

services:

  mongo:
    image: "${PLATFORM}mongo:${MONGO}"
    volumes:
      - front-tockmongo:/data/db
    ports:
      - "27017:27017"
    command: --bind_ip_all --port 27017 --replSet "tock"

  mongo2:
    image: "${PLATFORM}mongo:${MONGO}"
    depends_on:
      - mongo
    volumes:
      - front-tockmongo2:/data/db
    ports:
      - "27018:27018"
    command: --bind_ip_all --port 27018 --replSet "tock"

  mongo3:
    image: "${PLATFORM}mongo:${MONGO}"
    depends_on:
      - mongo
      - mongo2
    volumes:
      - front-tockmongo3:/data/db
    ports:
      - "27019:27019"
    command: --bind_ip_all --port 27019 --replSet "tock"

  mongo-setup:
    container_name: "mongo-setup-frontend"
    image: "${PLATFORM}mongo:${MONGO}"
    depends_on:
      - "mongo"
      - "mongo2"
      - "mongo3"
    links:
      - mongo:mongo
      - mongo2:mongo2
      - mongo3:mongo3
    volumes:
      - ./scripts:/scripts
    environment:
      - MONGO1=mongo
      - MONGO2=mongo2
      - MONGO3=mongo3
      - RS=tock
    entrypoint: [ "/scripts/setup.sh" ]

  build_worker:
    image: "${PLATFORM}tock/build_worker:${TAG}"
    depends_on:
      - mongo
      - mongo2
      - mongo3
    environment:
      - tock_mongo_url=mongodb://mongo:27017,mongo2:27018,mongo3:27019/?replicaSet=tock
      - tock_env=prod
      - JAVA_ARGS=-Xmx1g -XX:MaxMetaspaceSize=256m
#      - tock_default_log_level=warn
#      - tock_service_log_level=info
#      - tock_database_log_level=warn

  duckling:
    image: "${PLATFORM}tock/duckling:${TAG}"
    environment:
      - tock_env=prod
#      - tock_default_log_level=warn
#      - tock_service_log_level=info
#      - tock_database_log_level=warn
    expose:
      - "8080"

  kotlin_compiler:
    image: "${PLATFORM}tock/kotlin_compiler:${TAG}"
    environment:
      - tock_env=prod
      - tock_kotlin_compiler_classpath=/maven
#      - tock_default_log_level=warn
#      - tock_service_log_level=info
#      - tock_database_log_level=warn
    expose:
      - "8080"

  admin_web:
    image: "${PLATFORM}tock/bot_admin:${TAG}"
    depends_on:
      - mongo
      - mongo2
      - mongo3
      - duckling
      - kotlin_compiler
    environment:
      - tock_mongo_url=mongodb://mongo:27017,mongo2:27018,mongo3:27019/?replicaSet=tock
      - nlp_duckling_url=http://duckling:8080
      - tock_env=prod
      - tock_bot_admin_rest_default_base_url=http://bot_api:8080
      - tock_bot_compiler_service_url=http://kotlin_compiler:8080
      - tock_configuration_bot_default_base_url=http://bot_api:8080
      #remove this in production
      - tock_https_env=false
      - botadminverticle_body_limit=-1
#      - tock_default_log_level=warn
#      - tock_service_log_level=info
#      - tock_database_log_level=warn
      - botadminverticle_body_limit=-1
      - tock_bot_rest_client_request_timeout_ms=500000000
      - tock_bot_api_timeout_in_ms=500000000
      - tock_api_timout_in_s=600
      - tock_bot_test_timeout_in_ms=500000000
      - 'tock_users=admin@app.com,nlpuser@arkea.com,botuser@arkea.com,admin@arkea.com,techadmin@arkea.com,user1@arkea.com,user2@arkea.com,nlpOnly@arkea.com,botOnly@arkea.com,faqNlpOnly@arkea.com,faqBotOnly@arkea.com'
      - 'tock_passwords=password,pwd,pwd,pwd,pwd,pwd,pwd,pwd,pwd,pwd,pwd'
      - 'tock_organizations=app,app,app,abei,abei,app,app,app,app,app,app'
      - 'tock_roles=faqNlpUser|faqBotUser|nlpUser|botUser|admin|technicalAdmin,nlpUser|botUser,nlpUser|botUser,admin,nlpUser|botUser|admin|technicalAdmin,nlpUser|botUser,nlpUser|botUser,nlpUser,botUser,faqNlpUser,faqNlpUser|faqBotUser'
      - tock_encrypt_pass=PWD123
      - tock_default_log_level=debug
    ports:
      - '7999:8080'

  nlp_api:
    image: "${PLATFORM}tock/nlp_api:${TAG}"
    depends_on:
      - mongo
      - mongo2
      - mongo3
      - duckling
    environment:
      - tock_mongo_url=mongodb://mongo:27017,mongo2:27018,mongo3:27019/?replicaSet=tock
      - nlp_duckling_url=http://duckling:8080
      - tock_env=prod
      - tock_web_use_default_cors_handler=true
      - tock_web_use_default_cors_handler_with_credentials=false
      - tock_web_use_default_cors_handler_url=*
#      - tock_default_log_level=warn
#      - tock_service_log_level=info
#      - tock_database_log_level=warn
      - tock_encrypt_pass=PWD123
      - tock_default_log_level=debug
    ports:
      - "8888:8080"

  bot_api:
    image: "${PLATFORM}tock/bot_api:${TAG}"
    depends_on:
      - mongo
      - mongo2
      - mongo3
      - nlp_api
    environment:
      - JAVA_ARGS=-Djava.library.path=/usr/local/lib/python3.8/site-packages/jep
      - tock_mongo_url=mongodb://mongo:27017,mongo2:27018,mongo3:27019/?replicaSet=tock
      - tock_nlp_service_url=http://nlp_api:8080
      - tock_env=integ
      - tock_websocket_enabled=true
      - tock_default_log_level=warn
      - tock_service_log_level=info
      - tock_database_log_level=warn
    ports:
      - "8080:8080"

volumes:
  front-tockmongo:
  front-tockmongo2:
  front-tockmongo3:
